// ── OpenAI Structured Outputs (response_format) — pure helpers ───────────────
//
// OCP's `/v1/chat/completions` (Class B.1, ADR 0006) advertises OpenAI compatibility but forwards
// to `claude -p`, which has no native `response_format`. Asked for JSON, the coding-assistant CLI
// typically replies with prose, a Markdown table, or a ```json fenced block — none of which is
// `JSON.parse`-able. These helpers implement the OpenAI `response_format` contract on top of that:
// detect the request, build a strict JSON-only steering instruction, then extract and validate the
// JSON the model returns. All functions here are pure (no I/O) so they are unit-tested directly;
// the retry loop that calls the model lives in server.mjs (runStructuredCompletion).
//
// Spec authority (B.1, ADR 0006): OpenAI chat/completions `response_format`
//   https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format
// No field or behaviour beyond that published shape is introduced.

export class StructuredOutputError extends Error {
  constructor(reason, raw) {
    super(`structured output could not be produced: ${reason}`);
    this.name = "StructuredOutputError";
    this.reason = reason;
    this.raw = raw;
  }
}

// Returns { mode: "schema", schema, name?, strict } | { mode: "json_object" } | null.
// Supports the OpenAI shapes: response_format:{type:"json_schema",json_schema:{schema,strict,name}}
// and response_format:{type:"json_object"}, plus a lenient response_format:{schema} fallback.
export function detectStructuredOutput(parsed) {
  const rf = parsed?.response_format;
  if (!rf || typeof rf !== "object") return null;
  if (rf.type === "json_schema") {
    const js = (rf.json_schema && typeof rf.json_schema === "object") ? rf.json_schema : {};
    const schema = js.schema || rf.schema || null;
    return { mode: "schema", schema, name: js.name, strict: js.strict === true };
  }
  if (rf.type === "json_object") return { mode: "json_object" };
  if (rf.schema && typeof rf.schema === "object") {
    return { mode: "schema", schema: rf.schema, strict: rf.strict === true };
  }
  return null;
}

export function jsonTypeOf(v) {
  if (v === null) return "null";
  if (Array.isArray(v)) return "array";
  return typeof v; // object | string | number | boolean
}

export function jsonTypeMatches(t, value) {
  switch (t) {
    case "string": return typeof value === "string";
    case "number": return typeof value === "number" && Number.isFinite(value);
    case "integer": return typeof value === "number" && Number.isInteger(value);
    case "boolean": return typeof value === "boolean";
    case "object": return value !== null && typeof value === "object" && !Array.isArray(value);
    case "array": return Array.isArray(value);
    case "null": return value === null;
    default: return true; // unknown type keyword → do not fail on it
  }
}

const jsonDeepEqual = (a, b) => JSON.stringify(a) === JSON.stringify(b);

// Minimal JSON-Schema validator: covers the subset OpenAI structured outputs use — type (incl.
// arrays of types / integer), required, properties, additionalProperties (no invented keys), items
// (list + tuple), enum, const, nullability (type:["x","null"] or nullable:true), min/maxItems.
// Unknown keywords ($ref/allOf/anyOf/…) are skipped rather than failing. Returns error strings ([] = valid).
export function validateJsonSchema(value, schema, path = "$", strict = false) {
  const errors = [];
  if (!schema || typeof schema !== "object") return errors;

  // Nullability takes precedence: a null value is valid whenever the schema permits null (its type
  // union includes "null", or nullable:true), regardless of enum/const. This mirrors OpenAI
  // structured-output behaviour — nullable fields accept null even when a bare enum (as generated by
  // Home Assistant's extended_openai_conversation) omits null from its value list.
  const allowsNull = schema.nullable === true
    || (Array.isArray(schema.type) ? schema.type.includes("null") : schema.type === "null");
  if (value === null && allowsNull) return errors;

  if (Array.isArray(schema.enum) && !schema.enum.some(e => jsonDeepEqual(e, value))) {
    errors.push(`${path}: not one of the allowed enum values`);
  }
  if ("const" in schema && !jsonDeepEqual(schema.const, value)) {
    errors.push(`${path}: does not equal the required const value`);
  }

  if (schema.type !== undefined) {
    const types = Array.isArray(schema.type) ? schema.type : [schema.type];
    const nullable = schema.nullable === true || types.includes("null");
    const ok = types.some(t => jsonTypeMatches(t, value)) || (value === null && nullable);
    if (!ok) {
      errors.push(`${path}: expected ${types.join("|")}${schema.nullable ? "|null" : ""}, got ${jsonTypeOf(value)}`);
      return errors; // type mismatch — deeper checks are meaningless
    }
  }
  if (value === null) return errors;

  const vt = jsonTypeOf(value);
  if (vt === "object") {
    const props = schema.properties || {};
    for (const r of (schema.required || [])) {
      if (!Object.prototype.hasOwnProperty.call(value, r)) errors.push(`${path}.${r}: required property missing`);
    }
    const addl = schema.additionalProperties;
    const noExtra = addl === false || (strict && addl === undefined);
    for (const k of Object.keys(value)) {
      if (props[k]) {
        errors.push(...validateJsonSchema(value[k], props[k], `${path}.${k}`, strict));
      } else if (noExtra) {
        errors.push(`${path}.${k}: additional property not allowed`);
      } else if (addl && typeof addl === "object") {
        errors.push(...validateJsonSchema(value[k], addl, `${path}.${k}`, strict));
      }
    }
  } else if (vt === "array" && schema.items) {
    if (Array.isArray(schema.items)) {
      schema.items.forEach((s, i) => { if (i < value.length) errors.push(...validateJsonSchema(value[i], s, `${path}[${i}]`, strict)); });
    } else {
      value.forEach((item, i) => errors.push(...validateJsonSchema(item, schema.items, `${path}[${i}]`, strict)));
    }
    if (typeof schema.minItems === "number" && value.length < schema.minItems) errors.push(`${path}: fewer items than minItems ${schema.minItems}`);
    if (typeof schema.maxItems === "number" && value.length > schema.maxItems) errors.push(`${path}: more items than maxItems ${schema.maxItems}`);
  }
  return errors;
}

function tryJsonParse(s) {
  try { return { ok: true, value: JSON.parse(s) }; } catch { return { ok: false }; }
}

// Best-effort extraction of a single JSON value from model text: trims, strips one Markdown code
// fence, tries a direct parse, then falls back to a bracket-balanced slice from the first { or [
// (string-aware: brackets inside quoted strings are ignored). Returns { ok:true, value } | { ok:false }.
export function extractJsonPayload(text) {
  if (typeof text !== "string") return { ok: false };
  let s = text.trim();
  const fence = s.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  if (fence) s = fence[1].trim();

  const direct = tryJsonParse(s);
  if (direct.ok) return direct;

  let start = -1;
  for (let i = 0; i < s.length; i++) { if (s[i] === "{" || s[i] === "[") { start = i; break; } }
  if (start === -1) return { ok: false };

  let depth = 0, inStr = false, esc = false;
  for (let i = start; i < s.length; i++) {
    const c = s[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') { inStr = true; continue; }
    if (c === "{" || c === "[") depth++;
    else if (c === "}" || c === "]") { depth--; if (depth === 0) return tryJsonParse(s.slice(start, i + 1)); }
  }
  return { ok: false };
}

// The strict JSON-only system instruction appended to the request (attempt 0), escalated with the
// prior failure reason on retries.
export function structuredSystemInstruction(structured, attempt, lastErr) {
  const schemaBlock = (structured.mode === "schema" && structured.schema)
    ? `Your JSON MUST validate EXACTLY against this JSON Schema:\n${JSON.stringify(structured.schema)}\n`
      + `- Include every required property.\n`
      + `- Do NOT add any property that is not defined in the schema.\n`
      + `- Respect all declared types, enums, and nullability.`
    : `Respond with a single valid JSON value.`;
  let text =
`You are a strict JSON generator. Output a SINGLE JSON value and NOTHING else.
- The response MUST begin with { or [ and end with the matching } or ].
- Do NOT wrap the JSON in Markdown or code fences (no \`\`\`).
- Do NOT include any prose, explanation, heading, comment, reasoning, or XML — only the raw JSON.
${schemaBlock}`;
  if (attempt > 0) {
    text = `YOUR PREVIOUS RESPONSE WAS REJECTED (${lastErr}). Output ONLY the corrected raw JSON now, with no other text.\n\n` + text;
  }
  return text;
}
